version: '3.9'

services:
  app:
    image: ruluexample-app:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge